# src/test/resources/application-test.yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: dummy-test-secret-key-test-for
  access-token-expiration-seconds: 1
  refresh-token-expiration-seconds: 1